# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'First.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from checkcombobox import *


class FirstMainWindow(object):
    def first_setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1305, 708)
        MainWindow.setStyleSheet("background-color: rgb(255, 0, 0)qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("\n"
"alternate-background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        #self.sort = CheckableComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        #sizePolicy.setHeightForWidth(self.sort.sizePolicy().hasHeightForWidth())
        #self.sort.setSizePolicy(sizePolicy)
        #self.sort.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        #self.sort.setFont(font)
        #self.sort.setObjectName("sort")
        #self.gridLayout.addWidget(self.sort, 2, 4, 1, 1)
        self.transfer = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transfer.sizePolicy().hasHeightForWidth())
        self.transfer.setSizePolicy(sizePolicy)
        self.transfer.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.transfer.setFont(font)
        self.transfer.setObjectName("transfer")
        self.transfer.addItem("")
        self.transfer.addItem("")
        self.transfer.addItem("")
        self.transfer.addItem("")
        self.transfer.addItem("")
        self.gridLayout.addWidget(self.transfer, 0, 4, 1, 1)
        self.done = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.done.sizePolicy().hasHeightForWidth())
        self.done.setSizePolicy(sizePolicy)
        self.done.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.done.setFont(font)
        self.done.setObjectName("done")
        self.gridLayout.addWidget(self.done, 2, 5, 1, 1)
        self.createtask = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createtask.sizePolicy().hasHeightForWidth())
        self.createtask.setSizePolicy(sizePolicy)
        self.createtask.setMaximumSize(QtCore.QSize(250, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.createtask.setFont(font)
        self.createtask.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.createtask.setCheckable(False)
        self.createtask.setObjectName("createtask")
        self.gridLayout.addWidget(self.createtask, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.all = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.all.sizePolicy().hasHeightForWidth())
        self.all.setSizePolicy(sizePolicy)
        self.all.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.all.setFont(font)
        self.all.setObjectName("all")
        self.gridLayout.addWidget(self.all, 0, 5, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMaximumSize(QtCore.QSize(250, 40))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 2, 1, 1)
        self.bookingNo = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bookingNo.sizePolicy().hasHeightForWidth())
        self.bookingNo.setSizePolicy(sizePolicy)
        self.bookingNo.setMaximumSize(QtCore.QSize(250, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bookingNo.setFont(font)
        self.bookingNo.setObjectName("bookingNo")
        self.gridLayout.addWidget(self.bookingNo, 0, 2, 1, 1)
        self.edit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit.sizePolicy().hasHeightForWidth())
        self.edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.edit.setFont(font)
        self.edit.setObjectName("edit")
        self.gridLayout.addWidget(self.edit, 4, 4, 1, 2)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 3, 0, 1, 6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1305, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.first_retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def first_retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "J&J Global Express Sdn Bhd"))
        self.transfer.setItemText(0, _translate("MainWindow", "SI"))
        self.transfer.setItemText(1, _translate("MainWindow", "SE"))
        self.transfer.setItemText(2, _translate("MainWindow", "AI"))
        self.transfer.setItemText(3, _translate("MainWindow", "AE"))
        self.transfer.setItemText(4, _translate("MainWindow", "TE"))
        self.done.setText(_translate("MainWindow", "DONE"))
        self.createtask.setText(_translate("MainWindow", "CREATE TASK"))
        self.label.setText(_translate("MainWindow", "BOOKING NUMBER"))
        self.all.setText(_translate("MainWindow", "ALL"))
        self.edit.setText(_translate("MainWindow", "EDIT"))


