# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fourth.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class FourthMainWindow(object):
    def fourth_setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1126, 776)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4.sizePolicy().hasHeightForWidth())
        self.label4.setSizePolicy(sizePolicy)
        self.label4.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label4.setFont(font)
        self.label4.setObjectName("label4")
        self.gridLayout.addWidget(self.label4, 4, 0, 1, 2)
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3.sizePolicy().hasHeightForWidth())
        self.label3.setSizePolicy(sizePolicy)
        self.label3.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.gridLayout.addWidget(self.label3, 3, 0, 1, 2)
        self.label5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label5.sizePolicy().hasHeightForWidth())
        self.label5.setSizePolicy(sizePolicy)
        self.label5.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label5.setFont(font)
        self.label5.setObjectName("label5")
        self.gridLayout.addWidget(self.label5, 5, 0, 1, 2)
        self.label8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label8.sizePolicy().hasHeightForWidth())
        self.label8.setSizePolicy(sizePolicy)
        self.label8.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label8.setFont(font)
        self.label8.setObjectName("label8")
        self.gridLayout.addWidget(self.label8, 7, 0, 1, 2)
        self.label7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label7.sizePolicy().hasHeightForWidth())
        self.label7.setSizePolicy(sizePolicy)
        self.label7.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label7.setFont(font)
        self.label7.setObjectName("label7")
        self.gridLayout.addWidget(self.label7, 6, 0, 1, 2)
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2.sizePolicy().hasHeightForWidth())
        self.label2.setSizePolicy(sizePolicy)
        self.label2.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 2, 0, 1, 2)
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        self.label1.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 1, 0, 1, 2)
        self.done = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.done.sizePolicy().hasHeightForWidth())
        self.done.setSizePolicy(sizePolicy)
        self.done.setMinimumSize(QtCore.QSize(0, 35))
        self.done.setObjectName("done")
        self.gridLayout.addWidget(self.done, 0, 7, 1, 1)
        self.label10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label10.setFont(font)
        self.label10.setObjectName("label10")
        self.gridLayout.addWidget(self.label10, 0, 0, 1, 5)
        self.add = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add.sizePolicy().hasHeightForWidth())
        self.add.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.add.setFont(font)
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 8, 4, 1, 1)
        self.label9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label9.sizePolicy().hasHeightForWidth())
        self.label9.setSizePolicy(sizePolicy)
        self.label9.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label9.setFont(font)
        self.label9.setObjectName("label9")
        self.gridLayout.addWidget(self.label9, 8, 0, 1, 2)
        self.origin = QtWidgets.QLineEdit(self.centralwidget)
        self.origin.setMinimumSize(QtCore.QSize(150, 0))
        self.origin.setMaximumSize(QtCore.QSize(350, 16777215))
        self.origin.setText("")
        self.origin.setObjectName("origin")
        self.gridLayout.addWidget(self.origin, 6, 2, 1, 1)
        self.delete_ = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_.sizePolicy().hasHeightForWidth())
        self.delete_.setSizePolicy(sizePolicy)
        self.delete_.setMinimumSize(QtCore.QSize(0, 35))
        self.delete_.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.delete_.setFont(font)
        self.delete_.setObjectName("delete_")
        self.gridLayout.addWidget(self.delete_, 10, 1, 1, 1)
        self.edit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit.sizePolicy().hasHeightForWidth())
        self.edit.setSizePolicy(sizePolicy)
        self.edit.setMinimumSize(QtCore.QSize(0, 35))
        self.edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.edit.setFont(font)
        self.edit.setObjectName("edit")
        self.gridLayout.addWidget(self.edit, 10, 0, 1, 1)
        self.jjno = QtWidgets.QLineEdit(self.centralwidget)
        self.jjno.setMinimumSize(QtCore.QSize(150, 0))
        self.jjno.setMaximumSize(QtCore.QSize(350, 16777215))
        self.jjno.setObjectName("jjno")
        self.gridLayout.addWidget(self.jjno, 2, 2, 1, 1)
        self.containerno = QtWidgets.QLineEdit(self.centralwidget)
        self.containerno.setMinimumSize(QtCore.QSize(150, 0))
        self.containerno.setMaximumSize(QtCore.QSize(350, 16777215))
        self.containerno.setObjectName("containerno")
        self.gridLayout.addWidget(self.containerno, 8, 2, 1, 1)
        self.jobfileno = QtWidgets.QLineEdit(self.centralwidget)
        self.jobfileno.setMinimumSize(QtCore.QSize(150, 0))
        self.jobfileno.setMaximumSize(QtCore.QSize(350, 16777215))
        self.jobfileno.setObjectName("jobfileno")
        self.gridLayout.addWidget(self.jobfileno, 1, 2, 1, 1)
        self.shipper = QtWidgets.QLineEdit(self.centralwidget)
        self.shipper.setMinimumSize(QtCore.QSize(150, 0))
        self.shipper.setMaximumSize(QtCore.QSize(350, 16777215))
        self.shipper.setObjectName("shipper")
        self.gridLayout.addWidget(self.shipper, 3, 2, 1, 1)
        self.transfer = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transfer.sizePolicy().hasHeightForWidth())
        self.transfer.setSizePolicy(sizePolicy)
        self.transfer.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.transfer.setFont(font)
        self.transfer.setObjectName("transfer")
        self.transfer.addItem("")
        self.transfer.addItem("")
        self.transfer.addItem("")
        self.transfer.addItem("")
        self.transfer.addItem("")
        self.gridLayout.addWidget(self.transfer, 0, 6, 1, 1)
        self.consignee = QtWidgets.QLineEdit(self.centralwidget)
        self.consignee.setMinimumSize(QtCore.QSize(150, 0))
        self.consignee.setMaximumSize(QtCore.QSize(350, 16777215))
        self.consignee.setObjectName("consignee")
        self.gridLayout.addWidget(self.consignee, 4, 2, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 9, 0, 1, 3)
        self.bookingno = QtWidgets.QLineEdit(self.centralwidget)
        self.bookingno.setMinimumSize(QtCore.QSize(150, 0))
        self.bookingno.setMaximumSize(QtCore.QSize(350, 16777215))
        self.bookingno.setObjectName("bookingno")
        self.gridLayout.addWidget(self.bookingno, 5, 2, 1, 1)
        self.destination = QtWidgets.QLineEdit(self.centralwidget)
        self.destination.setMinimumSize(QtCore.QSize(150, 0))
        self.destination.setMaximumSize(QtCore.QSize(350, 16777215))
        self.destination.setObjectName("destination")
        self.gridLayout.addWidget(self.destination, 7, 2, 1, 1)
        self.back = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back.sizePolicy().hasHeightForWidth())
        self.back.setSizePolicy(sizePolicy)
        self.back.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.back.setFont(font)
        self.back.setObjectName("back")
        self.gridLayout.addWidget(self.back, 10, 6, 1, 1)
        self.upload = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload.sizePolicy().hasHeightForWidth())
        self.upload.setSizePolicy(sizePolicy)
        self.upload.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.upload.setFont(font)
        self.upload.setObjectName("upload")
        self.gridLayout.addWidget(self.upload, 10, 7, 1, 1)
        self.deleteall = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteall.sizePolicy().hasHeightForWidth())
        self.deleteall.setSizePolicy(sizePolicy)
        self.deleteall.setMinimumSize(QtCore.QSize(0, 35))
        self.deleteall.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.deleteall.setFont(font)
        self.deleteall.setObjectName("deleteall")
        self.gridLayout.addWidget(self.deleteall, 10, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1126, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.fourth_retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def fourth_retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "J&J Global Express Sdn Bhd"))
        self.label4.setText(_translate("MainWindow", "Consignee:"))
        self.label3.setText(_translate("MainWindow", "Shipper:"))
        self.label5.setText(_translate("MainWindow", "Booking No:"))
        self.label8.setText(_translate("MainWindow", "Destination:"))
        self.label7.setText(_translate("MainWindow", "Origin:"))
        self.label2.setText(_translate("MainWindow", "JJ No:"))
        self.label1.setText(_translate("MainWindow", "Job File No:"))
        self.done.setText(_translate("MainWindow", "DONE"))
        self.label10.setText(_translate("MainWindow", "Truck Task"))
        self.add.setText(_translate("MainWindow", "ADD"))
        self.label9.setText(_translate("MainWindow", "Enter an container No:"))
        self.delete_.setText(_translate("MainWindow", "DELETE"))
        self.edit.setText(_translate("MainWindow", "EDIT"))
        self.transfer.setItemText(0, _translate("MainWindow", "SI"))
        self.transfer.setItemText(1, _translate("MainWindow", "SE"))
        self.transfer.setItemText(2, _translate("MainWindow", "AI"))
        self.transfer.setItemText(3, _translate("MainWindow", "AE"))
        self.transfer.setItemText(4, _translate("MainWindow", "TE"))
        self.back.setText(_translate("MainWindow", "BACK"))
        self.upload.setText(_translate("MainWindow", "UPLOAD"))
        self.deleteall.setText(_translate("MainWindow", "DELETE ALL"))


