# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sixth.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class SixthMainWindow(object):
    def sixth_setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1041, 797)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 3, 0, 1, 1)
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.gridLayout.addWidget(self.label3, 4, 0, 1, 1)
        self.jjno = QtWidgets.QLineEdit(self.centralwidget)
        self.jjno.setMaximumSize(QtCore.QSize(400, 16777215))
        self.jjno.setObjectName("jjno")
        self.gridLayout.addWidget(self.jjno, 3, 1, 1, 2)
        self.jobfileno = QtWidgets.QLineEdit(self.centralwidget)
        self.jobfileno.setMaximumSize(QtCore.QSize(400, 16777215))
        self.jobfileno.setObjectName("jobfileno")
        self.gridLayout.addWidget(self.jobfileno, 2, 1, 1, 2)
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 2, 0, 1, 1)
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label4.setFont(font)
        self.label4.setObjectName("label4")
        self.gridLayout.addWidget(self.label4, 5, 0, 1, 1)
        self.origin = QtWidgets.QLineEdit(self.centralwidget)
        self.origin.setMaximumSize(QtCore.QSize(400, 16777215))
        self.origin.setObjectName("origin")
        self.gridLayout.addWidget(self.origin, 7, 1, 1, 2)
        self.shipper = QtWidgets.QLineEdit(self.centralwidget)
        self.shipper.setMaximumSize(QtCore.QSize(400, 16777215))
        self.shipper.setObjectName("shipper")
        self.gridLayout.addWidget(self.shipper, 4, 1, 1, 2)
        self.label8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label8.setFont(font)
        self.label8.setObjectName("label8")
        self.gridLayout.addWidget(self.label8, 8, 0, 1, 1)
        self.deleteall = QtWidgets.QPushButton(self.centralwidget)
        self.deleteall.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.deleteall.setFont(font)
        self.deleteall.setObjectName("deleteall")
        self.gridLayout.addWidget(self.deleteall, 10, 4, 1, 1)
        self.label7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label7.setFont(font)
        self.label7.setObjectName("label7")
        self.gridLayout.addWidget(self.label7, 7, 0, 1, 1)
        self.awb = QtWidgets.QLineEdit(self.centralwidget)
        self.awb.setMaximumSize(QtCore.QSize(400, 16777215))
        self.awb.setObjectName("awb")
        self.gridLayout.addWidget(self.awb, 6, 1, 1, 2)
        self.destination = QtWidgets.QLineEdit(self.centralwidget)
        self.destination.setMaximumSize(QtCore.QSize(400, 16777215))
        self.destination.setObjectName("destination")
        self.gridLayout.addWidget(self.destination, 8, 1, 1, 2)
        self.label6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label6.setFont(font)
        self.label6.setObjectName("label6")
        self.gridLayout.addWidget(self.label6, 6, 0, 1, 1)
        self.back = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back.sizePolicy().hasHeightForWidth())
        self.back.setSizePolicy(sizePolicy)
        self.back.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.back.setFont(font)
        self.back.setObjectName("back")
        self.gridLayout.addWidget(self.back, 10, 2, 1, 1)
        self.update = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update.sizePolicy().hasHeightForWidth())
        self.update.setSizePolicy(sizePolicy)
        self.update.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.update.setFont(font)
        self.update.setObjectName("update")
        self.gridLayout.addWidget(self.update, 10, 3, 1, 1)
        self.consignee = QtWidgets.QLineEdit(self.centralwidget)
        self.consignee.setMaximumSize(QtCore.QSize(400, 16777215))
        self.consignee.setObjectName("consignee")
        self.gridLayout.addWidget(self.consignee, 5, 1, 1, 2)
        self.label10 = QtWidgets.QLabel(self.centralwidget)
        self.label10.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label10.setFont(font)
        self.label10.setObjectName("label10")
        self.gridLayout.addWidget(self.label10, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1041, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.sixth_retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def sixth_retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "J&J Global Express Sdn Bhd"))
        self.label2.setText(_translate("MainWindow", "JJ No:"))
        self.label3.setText(_translate("MainWindow", "Shipper:"))
        self.label1.setText(_translate("MainWindow", "Job File No:"))
        self.label4.setText(_translate("MainWindow", "Consignee:"))
        self.label8.setText(_translate("MainWindow", "Destination:"))
        self.deleteall.setText(_translate("MainWindow", "DELETE ALL"))
        self.label7.setText(_translate("MainWindow", "Origin:"))
        self.label6.setText(_translate("MainWindow", "AWB:"))
        self.back.setText(_translate("MainWindow", "BACK"))
        self.update.setText(_translate("MainWindow", "UPDATE"))
        self.label10.setText(_translate("MainWindow", "Air Task Edit"))


